import { createContext, useContext, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: "Dashboard", sales: "Sales", expenses: "Expenses", inventory: "Inventory",
    smartStaffing: "Smart Staffing", weatherSmart: "Weather Smart", wasteTracker: "Waste Tracker", weeklyReport: "Weekly Report",
    momsVat: "Tax/VAT", darkMode: "Dark Mode", lightMode: "Light Mode", signOut: "Sign Out",
    language: "Dansk",
    // Dashboard
    welcome: "Welcome", todayRevenue: "Today's Revenue", monthlyProfit: "Monthly Profit",
    topExpense: "Top Expense", inventoryAlerts: "Inventory Alerts", snapReceipt: "Snap Receipt",
    repeatYesterday: "Repeat Yesterday's Sale", downloadPdf: "Download PDF Report",
    loadingDashboard: "Loading dashboard...", vsYesterday: "vs yesterday", margin: "margin",
    none: "None", revenueTrend: "Revenue Trend", expenseBreakdown: "Expense Breakdown",
    noRevenueData: "No revenue data yet", noExpenseData: "No expense data yet",
    recentReceipts: "Recent Receipts", dailyGoal: "Daily Goal", monthlyGoal: "Monthly Target", reached: "Reached!",
    setDailyGoal: "Set a daily revenue goal", trackProgress: "Set a target to track progress",
    setGoal: "Set Goal", editGoal: "Edit goal", save: "Save", cancel: "Cancel",
    yesterdayCopied: "Yesterday's sale copied to today!", noYesterdaySale: "No sale found for yesterday",
    // Sales
    salesTracker: "Sales Tracker", logSale: "Log Today's Sale",
    tapAmount: "Tap an amount or type your own", customAmount: "Custom amount...", log: "Log",
    recentSales: "Recent Sales", date: "Date", amount: "Amount", payment: "Payment",
    noSalesYet: "No sales yet — tap an amount above to start!",
    importCsv: "Import from CSV", csvColumns: "Columns: date, amount, payment_method (optional)",
    uploading: "Uploading...", chooseFile: "Choose File",
    salesImported: "sales imported", rowsSkipped: "rows skipped",
    // Expenses
    expenseTracker: "Expense Tracker", addExpense: "Add Expense",
    pickCategory: "Pick a category, describe it, tap an amount",
    whatWasIt: "What was it? (e.g. Tomatoes, Electric bill)", add: "Add",
    recentExpenses: "Recent Expenses", description: "Description",
    noExpensesYet: "No expenses yet — pick a category and add one above!",
    firstTimeSetup: "First time? Set up common categories in one tap",
    setupCategories: "Set Up Categories",
    // Inventory
    inventoryMonitor: "Inventory Monitor", lowStockAlerts: "Low Stock Alerts", itemsBelowMinStock: "items below min stock",
    addItem: "Add Item", itemName: "Item name", quantity: "Quantity", unit: "Unit",
    costPerUnit: "Cost/Unit", threshold: "Threshold",
    pieces: "Pieces", kg: "Kg", liters: "Liters", boxes: "Boxes",
    noInventoryYet: "No inventory items yet",
    // Staffing
    analyzingPatterns: "Analyzing sales patterns...", notEnoughData: "Not enough sales data yet",
    logMoreSales: "Log at least a few weeks of sales to enable predictions",
    slowDaysAhead: "Slow Days Ahead", reduceStaff: "Reduce staff, prep less",
    normalDays: "Normal Days", standardStaffing: "Standard staffing",
    busyDaysAhead: "Busy Days Ahead", extraStaff: "Extra staff needed",
    revenueForecast: "Revenue Forecast & Recommended Staff", salesPatterns: "Your Sales Patterns",
    predictedRevenue: "Predicted Revenue", day: "Day", level: "Level",
    staffNeeded: "Staff Needed", confidence: "Confidence", staffingRules: "Staffing Rules",
    staffingRulesDesc: "Define how many staff you need at different revenue levels.",
    addRule: "Add Rule", remove: "Remove", staff: "staff",
    next7days: "Next 7 days", next14days: "Next 14 days", next30days: "Next 30 days",
    totalStaffNeeded: "Total Staff Needed", basedOnPatterns: "Based on predicted revenue patterns",
    minRevenue: "Min revenue", maxRevenue: "Max revenue",
    slow: "Slow", normal: "Normal", busy: "Busy",
    // Waste
    logWaste: "Log Waste", trackWaste: "Track what gets thrown out",
    wasteLogged: "Waste logged!", monthlyWasteCost: "Monthly Waste Cost",
    itemsWasted: "Items Wasted", noDataYet: "No data yet",
    whatWasWasted: "What was wasted? (e.g. Chicken breast)", qty: "Qty",
    estimatedCost: "Estimated cost (DKK)", customCost: "Custom cost...",
    recentWaste: "Recent Waste", item: "Item", reason: "Reason", cost: "Cost",
    noWasteYet: "No waste logged yet",
    expired: "expired", overcooked: "overcooked", damaged: "damaged", other: "other",
    // Weekly Report
    weeklySalesReport: "Weekly Sales Report", dailyAvg: "Daily Avg",
    daysRecorded: "Days Recorded", bestDay: "Best Day", slowestDay: "Slowest Day",
    revenue: "Revenue", vsLastWeek: "vs last week",
    loadingReport: "Loading report...", noSalesData: "No sales data available yet.",
    // VAT — these are now generic fallbacks; currency-specific terms come from getVatTerms()
    vatReport: "Tax Report", salesSection: "Sales",
    salesInclVat: "Sales incl. Tax", salesExclVat: "Sales excl. Tax",
    outputVat: "Output Tax", expensesSection: "Expenses",
    expensesInclVat: "Expenses incl. Tax",
    expensesExclVat: "Expenses excl. Tax",
    inputVat: "Input Tax", vatPayable: "Tax Payable",
    payableToSkat: "Amount payable to tax authority", refundFromSkat: "Tax refund",
    loadingVat: "Loading tax report...", vatError: "Could not load tax report.",
    // Receipt
    uploadReceipt: "Upload Receipt Photo", takePhoto: "Take Photo",
    photoOrGallery: "Take a photo or choose from gallery", scanningReceipt: "Scanning receipt...",
    detectedAmount: "Detected amount", couldntRead: "Couldn't read amount — type it manually below",
    ocrNotAvailable: "OCR not available — type the amount manually",
    enterTotal: "Enter total amount...", confirmLog: "Confirm & Log Sale",
    saleLoggedReceipt: "Sale logged from receipt!",
    // Quick Add
    quickEntry: "Quick Entry", logSaleTab: "Log Sale", addExpenseTab: "Add Expense",
    quickAmount: "Quick amount (DKK)", orTypeAmount: "Or type amount...",
    category: "Category", addCategoriesFirst: "Add categories in Expenses page first",
    whatForExpense: "What was it for? (e.g. Tomatoes)",
    saleLogged: "Sale logged!", expenseAdded: "Expense added!",
    // Forecast
    revenueForecastTitle: "Revenue Forecast", nextDays: "Next 7 Days",
    predictedTotal: "Predicted Total", avgDaily: "Avg/Day",
    trendUp: "Trending Up", trendDown: "Trending Down", trendStable: "Stable",
    forecastConfidence: "Confidence", noForecastData: "Need more sales data for predictions",
    predicted: "Predicted", actual: "Actual",
    // Feedback
    feedback: "Feedback", sendFeedback: "Send Feedback", yourFeedback: "Your Feedback",
    feedbackSent: "Thank you for your feedback!", rateExperience: "Rate your experience",
    feedbackMessage: "Tell us what you think...", bugReport: "Bug Report",
    featureRequest: "Feature Request", generalFeedback: "General Feedback",
    complaint: "Complaint", praise: "Praise", noFeedbackYet: "No feedback submitted yet",
    stars: "stars",
    // Payment methods
    cash: "Cash", card: "Card", mobilepay: "MobilePay", mixed: "Mixed",
    dankort: "Dankort", bankTransfer: "Bank Transfer",
    // Quick Sale
    quickSale: "Quick Sale",
    // Time periods
    today: "Today", thisWeek: "This Week", thisMonth: "This Month", last30Days: "Last 30 Days",
    // Layout / Nav
    businessMode: "Business Mode", personalMode: "Personal Mode",
    reports: "Reports", khata: "Khata", loanTracker: "Loan Tracker",
    // Common actions
    delete: "Delete", edit: "Edit", or: "or",
    search: "Search...", exportCsv: "Export CSV", clear: "Clear",
    noData: "No data", loading: "Loading...",
    // QuickAdd personal
    income: "Income", expense: "Expense", incomeSource: "Income Source",
    spendingCategory: "Spending Category", amountReceived: "Amount received",
    amountSpent: "Amount spent", notesOptional: "Notes (optional)",
    logIncome: "Log Income", logExpense: "Log Expense",
    incomeLogged: "Income logged!", expenseLogged: "Expense logged!",
    noIncomeCatsYet: "No income categories yet", noSpendCatsYet: "No spending categories yet",
    // Dashboard extras
    todaysProfit: "Today's Profit", thisWeekRevenue: "This Week's Revenue",
    thisWeekProfit: "This Week's Profit", thisMonthRevenue: "This Month's Revenue",
    thisMonthProfit: "This Month's Profit", last30Revenue: "Last 30 Days Revenue",
    last30Profit: "Last 30 Days Profit",
    profitability: "Profitability", consistency: "Consistency", growth: "Growth",
    costControl: "Cost Control", activity: "Activity",
    excellent: "Excellent", good: "Good", needsWork: "Needs Work", critical: "Critical",
    businessHealth: "Business Health", onTrack: "On Track", average: "Average",
    needsAttention: "Needs Attention", khataReceivable: "Khata Receivable",
    outstandingCredit: "Outstanding credit", daysActive: "days active",
    ofRevenue: "of revenue", activeToday: "Active today", noSalesToday: "No sales today",
    notProfitableYet: "Not profitable yet",
    // Inventory extras
    general: "General", itemAdded: "Item added!", itemUpdated: "Item updated!",
    stockAdded: "Stock added", stockRemoved: "Stock removed", itemDeleted: "Item deleted",
    // Expenses extras
    backdatedEntry: "Backdated entry", personalExpense: "Personal expense",
    businessExpense: "Business expense", excludedFromReports: "Excluded from reports & VAT",
    typeCustomCategory: "Type custom category...", moveToTrash: "Move to trash",
    actions: "Actions", notes: "Notes",
    // Cash Book
    cashBook: "Cash Book",
    // Contact
    contact: "Contact",
    // Recently Deleted
    recentlyDeleted: "Recently Deleted",
    // Profile
    profile: "Profile",
    // Cash Book page
    cashBalance: "Cash Balance", totalCashIn: "Total Cash In", totalCashOut: "Total Cash Out",
    cashIn: "Cash In", cashOut: "Cash Out", addIn: "Add In", addOut: "Add Out",
    whatWasItFor: "What was it for?", transactionHistory: "Transaction History",
    noCashTransactionsYet: "No cash transactions yet", autoSynced: "Auto-synced",
    updated: "Updated!", movedToDeleted: "Moved to recently deleted",
    // Khata page
    khataTitle: "Khata — Customer Ledger", khataSubtitle: "Track credit purchases and payments for your wholesale customers",
    totalReceivable: "Total Receivable", customers: "Customers", topDebtors: "Top Debtors",
    noPendingBalances: "No pending balances", searchCustomers: "Search customers...",
    noCustomersYet: "No customers yet", selectCustomer: "Select a customer",
    selectCustomerDesc: "Choose a customer from the list to view their ledger",
    owed: "owed", overpaid: "overpaid", settled: "Settled",
    recordPayment: "Record Payment", totalPurchased: "Total Purchased", totalPaid: "Total Paid",
    remaining: "Remaining", full: "Full", pay: "Pay",
    purchased: "Purchased", paid: "Paid", balance: "Balance",
    noTransactionsYet: "No transactions yet", addFirstAbove: "— add the first one above",
    update: "Update",
    // Loan Tracker page
    loanTrackerTitle: "Loan Tracker", loanTrackerSubtitle: "Track money borrowed and lent with partial payments",
    iOweBorrowed: "I Owe (Borrowed)", owedToMeLent: "Owed to Me (Lent)", netBalance: "Net Balance",
    people: "People", iLent: "I Lent", iBorrowed: "I Borrowed",
    repayment: "Repayment", repaid: "Repaid", lent: "Lent", borrowed: "Borrowed",
    iOwe: "I owe", owesMe: "Owes me",
    selectPerson: "Select a person", selectPersonDesc: "Choose someone from the list to view loan details",
    noPeopleYet: "No people yet",
    // Recently Deleted page
    restore: "Restore", deleteForever: "Delete Forever",
    noDeletedItems: "No deleted items", waste: "Waste",
    // Personal Finance page
    personalFinance: "Personal Finance", trackPersonalIncome: "Track your personal income and spending",
    setupPersonalCategories: "Set up personal categories", createCategories: "Create Categories",
    youHave: "You have", youreShort: "You're short", spent: "spent",
    loans: "Loans", owedToYou: "owed to you", youOwe: "you owe", netWorth: "Net Worth",
    balancePlusLoans: "balance + loans", budgetExceeded: "Budget Exceeded",
    over: "over", approachingBudgetLimit: "Approaching Budget Limit",
    used: "used", monthlyBudget: "Monthly Budget", setBudget: "Set Budget",
    hideBudgetSettings: "Hide Budget Settings", monthlyReport: "Monthly Report",
    hideMonthlyReport: "Hide Monthly Report", monthlyBudgetSettings: "Monthly Budget Settings",
    totalMonthlyBudget: "Total Monthly Budget", saveBudget: "Save Budget", saved: "Saved",
    incomeSources: "Income Sources", spendingByCategory: "Spending by Category",
    whereYourMoneyGoes: "Where your money goes", noSpendingData: "No spending data yet",
    noSpendingThisMonth: "No spending this month",
    financialSnapshot: "Financial Snapshot", viewLoanTracker: "View Loan Tracker →",
    savingsRate: "Savings Rate", loanEmiPaid: "Loan/EMI Paid",
    topPeople: "Top People", addEntry: "Add Entry", pickCategoryOrType: "Pick a category or type your own",
    greatMonth: "Great month! You saved well.", inTheGreen: "You're in the green, keep it up!",
    overspentThisMonth: "You overspent this month. Review your spending.",
    budgetExceededBy: "Budget exceeded by",
    // Reports page
    reportBuilder: "Report Builder", buildCustomReport: "Build a custom report and download as PDF",
    selectSections: "Select Sections", overviewAlwaysIncluded: "Overview is always included. Pick what else to add.",
    all: "All", noneSelect: "None", sectionsSelected: "sections selected",
    includingOverview: "including overview", downloadReportPdf: "Download Report PDF",
    generatingPdf: "Generating PDF...", reportsDisclaimer: "Reports are estimates for reference only.",
    dailyKasserapport: "Daily Kasserapport", kasserapport: "Kasserapport", subtotal: "Subtotal",
    totalInclVat: "Total", transactionCount: "Transactions", paymentBreakdown: "Payment Breakdown",
    kasseBalance: "Cash Register Balance", printReport: "Print", dailyReport: "Daily Report",
    expensesTotal: "Expenses", netCash: "Net Cash", noSalesOnDate: "No sales on this date",
    monthlyReport: "Monthly Report",
    salesBreakdown: "Sales Breakdown", expenseBreakdownReport: "Expense Breakdown",
    inventoryReport: "Inventory Report", khataSummary: "Khata Summary",
    cashFlow: "Cash Flow", wasteReport: "Waste Report", staffRules: "Staff Rules",
    stockValue: "Stock Value", khataOutstanding: "Khata Outstanding",
    creditOwed: "Credit owed", lowStock: "low stock",
    netProfit: "Net Profit",
    // Inventory extras
    loadTemplate: "Load Template", stockItems: "Stock Items", searchItems: "Search items...",
    totalItems: "Total Items", freshItems: "Fresh Items", categories: "Categories",
    priced: "Priced", stockCost: "Stock Cost", potentialRevenue: "Potential Revenue",
    potentialProfit: "Potential Profit", avgMargin: "Avg Margin",
    invested: "invested", ifAllSold: "if all sold", itemsPriced: "items priced",
    filteredBy: "Filtered by", showAll: "Show all", minStock: "Min Stock",
    freshItem: "Fresh item", bundle: "Bundle", dozen: "Dozen",
    categoryPlaceholder: "e.g. Beverages, Dairy",
    // Months
    january: "January", february: "February", march: "March", april: "April",
    may: "May", june: "June", july: "July", august: "August",
    september: "September", october: "October", november: "November", december: "December",
  },
  da: {
    dashboard: "Oversigt", sales: "Salg", expenses: "Udgifter", inventory: "Lager",
    smartStaffing: "Vagtplanlægning", weatherSmart: "Vejr Smart", wasteTracker: "Madspild", weeklyReport: "Ugerapport",
    momsVat: "Moms", darkMode: "Mørk tilstand", lightMode: "Lys tilstand", signOut: "Log ud",
    language: "English",
    // Dashboard
    welcome: "Velkommen", todayRevenue: "Dagens omsætning", monthlyProfit: "Månedens overskud",
    topExpense: "Største udgift", inventoryAlerts: "Lageradvarsler", snapReceipt: "Tag kvittering",
    repeatYesterday: "Gentag gårsdagens salg", downloadPdf: "Hent PDF-rapport",
    loadingDashboard: "Indlæser oversigt...", vsYesterday: "vs i går", margin: "margin",
    none: "Ingen", revenueTrend: "Omsætningsudvikling", expenseBreakdown: "Udgiftsfordeling",
    noRevenueData: "Ingen omsætningsdata endnu", noExpenseData: "Ingen udgiftsdata endnu",
    recentReceipts: "Seneste kvitteringer", dailyGoal: "Dagligt mål", monthlyGoal: "Månedligt mål", reached: "Nået!",
    setDailyGoal: "Sæt et dagligt omsætningsmål", trackProgress: "Sæt et mål for at følge fremskridt",
    setGoal: "Sæt mål", editGoal: "Rediger mål", save: "Gem", cancel: "Annuller",
    yesterdayCopied: "Gårsdagens salg kopieret til i dag!", noYesterdaySale: "Intet salg fundet for i går",
    // Sales
    salesTracker: "Salgsregistrering", logSale: "Registrer dagens salg",
    tapAmount: "Tryk på et beløb eller skriv dit eget", customAmount: "Brugerdefineret beløb...",
    log: "Registrer", recentSales: "Seneste salg", date: "Dato", amount: "Beløb",
    payment: "Betaling", noSalesYet: "Ingen salg endnu — tryk på et beløb ovenfor!",
    importCsv: "Importer fra CSV", csvColumns: "Kolonner: dato, beløb, betalingsmetode (valgfri)",
    uploading: "Uploader...", chooseFile: "Vælg fil",
    salesImported: "salg importeret", rowsSkipped: "rækker sprunget over",
    // Expenses
    expenseTracker: "Udgiftsregistrering", addExpense: "Tilføj udgift",
    pickCategory: "Vælg en kategori, beskriv den, tryk på et beløb",
    whatWasIt: "Hvad var det? (f.eks. Tomater, Elregning)", add: "Tilføj",
    recentExpenses: "Seneste udgifter", description: "Beskrivelse",
    noExpensesYet: "Ingen udgifter endnu — vælg en kategori og tilføj ovenfor!",
    firstTimeSetup: "Første gang? Opret standardkategorier med ét tryk",
    setupCategories: "Opret kategorier",
    // Inventory
    inventoryMonitor: "Lageroversigt", lowStockAlerts: "Advarsler om lav beholdning", itemsBelowMinStock: "varer under minimum",
    addItem: "Tilføj vare", itemName: "Varenavn", quantity: "Antal", unit: "Enhed",
    costPerUnit: "Pris/enhed", threshold: "Grænseværdi",
    pieces: "Styk", kg: "Kg", liters: "Liter", boxes: "Kasser",
    noInventoryYet: "Ingen lagervarer endnu",
    // Staffing
    analyzingPatterns: "Analyserer salgsmønstre...", notEnoughData: "Ikke nok salgsdata endnu",
    logMoreSales: "Registrer mindst et par ugers salg for at aktivere forudsigelser",
    slowDaysAhead: "Rolige dage forude", reduceStaff: "Reducer personale, forbered mindre",
    normalDays: "Normale dage", standardStaffing: "Standard bemanding",
    busyDaysAhead: "Travle dage forude", extraStaff: "Ekstra personale nødvendigt",
    revenueForecast: "Omsætningsprognose & anbefalet bemanding", salesPatterns: "Dine salgsmønstre",
    predictedRevenue: "Forventet omsætning", day: "Dag", level: "Niveau",
    staffNeeded: "Personale", confidence: "Sikkerhed", staffingRules: "Bemandingsregler",
    staffingRulesDesc: "Definer hvor mange ansatte du har brug for ved forskellige omsætningsniveauer.",
    addRule: "Tilføj regel", remove: "Fjern", staff: "personale",
    next7days: "Næste 7 dage", next14days: "Næste 14 dage", next30days: "Næste 30 dage",
    totalStaffNeeded: "Samlet personale nødvendigt", basedOnPatterns: "Baseret på forventede omsætningsmønstre",
    minRevenue: "Min. omsætning", maxRevenue: "Maks. omsætning",
    slow: "Rolig", normal: "Normal", busy: "Travl",
    // Waste
    logWaste: "Registrer spild", trackWaste: "Hold styr på hvad der smides ud",
    wasteLogged: "Spild registreret!", monthlyWasteCost: "Månedlig spildudgift",
    itemsWasted: "Varer smidt ud", noDataYet: "Ingen data endnu",
    whatWasWasted: "Hvad blev smidt ud? (f.eks. Kyllingebryst)", qty: "Antal",
    estimatedCost: "Anslået pris (DKK)", customCost: "Brugerdefineret pris...",
    recentWaste: "Seneste spild", item: "Vare", reason: "Årsag", cost: "Pris",
    noWasteYet: "Intet spild registreret endnu",
    expired: "udløbet", overcooked: "overkogt", damaged: "beskadiget", other: "andet",
    // Weekly Report
    weeklySalesReport: "Ugentlig salgsrapport", dailyAvg: "Dagligt gns.",
    daysRecorded: "Dage registreret", bestDay: "Bedste dag", slowestDay: "Langsomste dag",
    revenue: "Omsætning", vsLastWeek: "vs sidste uge",
    loadingReport: "Indlæser rapport...", noSalesData: "Ingen salgsdata tilgængelig endnu.",
    // VAT — generic Danish fallbacks; currency-specific terms come from getVatTerms()
    vatReport: "Momsopgørelse", salesSection: "Salg",
    salesInclVat: "Salg inkl. moms", salesExclVat: "Salg ekskl. moms",
    outputVat: "Udgående moms", expensesSection: "Udgifter",
    expensesInclVat: "Udgifter inkl. moms", expensesExclVat: "Udgifter ekskl. moms",
    inputVat: "Indgående moms", vatPayable: "Moms til betaling",
    payableToSkat: "Beløb der skal indbetales til SKAT", refundFromSkat: "Beløb til gode fra SKAT",
    loadingVat: "Indlæser momsrapport...", vatError: "Kunne ikke indlæse momsrapporten.",
    // Receipt
    uploadReceipt: "Upload kvitteringsbillede", takePhoto: "Tag billede",
    photoOrGallery: "Tag et billede eller vælg fra galleri", scanningReceipt: "Scanner kvittering...",
    detectedAmount: "Registreret beløb", couldntRead: "Kunne ikke læse beløb — skriv det manuelt nedenfor",
    ocrNotAvailable: "OCR ikke tilgængelig — skriv beløbet manuelt",
    enterTotal: "Indtast totalbeløb...", confirmLog: "Bekræft & registrer salg",
    saleLoggedReceipt: "Salg registreret fra kvittering!",
    // Quick Add
    quickEntry: "Hurtig registrering", logSaleTab: "Registrer salg", addExpenseTab: "Tilføj udgift",
    quickAmount: "Hurtigt beløb (DKK)", orTypeAmount: "Eller skriv beløb...",
    category: "Kategori", addCategoriesFirst: "Tilføj kategorier på udgiftssiden først",
    whatForExpense: "Hvad var det til? (f.eks. Tomater)",
    saleLogged: "Salg registreret!", expenseAdded: "Udgift tilføjet!",
    // Forecast
    revenueForecastTitle: "Omsætningsprognose", nextDays: "Næste 7 dage",
    predictedTotal: "Forventet total", avgDaily: "Gns./dag",
    trendUp: "Stigende", trendDown: "Faldende", trendStable: "Stabil",
    forecastConfidence: "Sikkerhed", noForecastData: "Flere salgsdata nødvendige for prognoser",
    predicted: "Forventet", actual: "Faktisk",
    // Feedback
    feedback: "Tilbagemelding", sendFeedback: "Send tilbagemelding", yourFeedback: "Din tilbagemelding",
    feedbackSent: "Tak for din tilbagemelding!", rateExperience: "Bedøm din oplevelse",
    feedbackMessage: "Fortæl os hvad du synes...", bugReport: "Fejlrapport",
    featureRequest: "Funktionsønske", generalFeedback: "Generel tilbagemelding",
    complaint: "Klage", praise: "Ros", noFeedbackYet: "Ingen tilbagemelding endnu",
    stars: "stjerner",
    // Payment methods
    cash: "Kontant", card: "Kort", mobilepay: "MobilePay", mixed: "Blandet",
    dankort: "Dankort", bankTransfer: "Bankoverførsel",
    // Quick Sale
    quickSale: "Hurtig salg",
    // Time periods
    today: "I dag", thisWeek: "Denne uge", thisMonth: "Denne måned", last30Days: "Sidste 30 dage",
    // Layout / Nav
    businessMode: "Virksomhed", personalMode: "Personlig",
    reports: "Rapporter", khata: "Khata", loanTracker: "Lånoversigt",
    // Common actions
    delete: "Slet", edit: "Rediger", or: "eller",
    search: "Søg...", exportCsv: "Eksporter CSV", clear: "Ryd",
    noData: "Ingen data", loading: "Indlæser...",
    // QuickAdd personal
    income: "Indkomst", expense: "Udgift", incomeSource: "Indkomstkilde",
    spendingCategory: "Udgiftskategori", amountReceived: "Beløb modtaget",
    amountSpent: "Beløb brugt", notesOptional: "Noter (valgfri)",
    logIncome: "Registrer indkomst", logExpense: "Registrer udgift",
    incomeLogged: "Indkomst registreret!", expenseLogged: "Udgift registreret!",
    noIncomeCatsYet: "Ingen indkomstkategorier endnu", noSpendCatsYet: "Ingen udgiftskategorier endnu",
    // Dashboard extras
    todaysProfit: "Dagens overskud", thisWeekRevenue: "Ugens omsætning",
    thisWeekProfit: "Ugens overskud", thisMonthRevenue: "Månedens omsætning",
    thisMonthProfit: "Månedens overskud", last30Revenue: "Sidste 30 dages omsætning",
    last30Profit: "Sidste 30 dages overskud",
    profitability: "Rentabilitet", consistency: "Konsistens", growth: "Vækst",
    costControl: "Omkostningskontrol", activity: "Aktivitet",
    excellent: "Fremragende", good: "God", needsWork: "Behøver arbejde", critical: "Kritisk",
    businessHealth: "Virksomhedshelbred", onTrack: "På rette spor", average: "Gennemsnitlig",
    needsAttention: "Kræver opmærksomhed", khataReceivable: "Khata tilgodehavende",
    outstandingCredit: "Udestående kredit", daysActive: "dage aktiv",
    ofRevenue: "af omsætning", activeToday: "Aktiv i dag", noSalesToday: "Intet salg i dag",
    notProfitableYet: "Ikke rentabel endnu",
    // Inventory extras
    general: "Generelt", itemAdded: "Vare tilføjet!", itemUpdated: "Vare opdateret!",
    stockAdded: "Lager tilføjet", stockRemoved: "Lager fjernet", itemDeleted: "Vare slettet",
    // Expenses extras
    backdatedEntry: "Tilbagedateret post", personalExpense: "Personlig udgift",
    businessExpense: "Forretningsudgift", excludedFromReports: "Ekskluderet fra rapporter & moms",
    typeCustomCategory: "Skriv egen kategori...", moveToTrash: "Flyt til papirkurv",
    actions: "Handlinger", notes: "Noter",
    // Cash Book
    cashBook: "Kassebog",
    // Contact
    contact: "Kontakt",
    // Recently Deleted
    recentlyDeleted: "Nyligt slettet",
    profile: "Profil",
    // Cash Book page
    cashBalance: "Kassebeholdning", totalCashIn: "Total indgående", totalCashOut: "Total udgående",
    cashIn: "Indgående", cashOut: "Udgående", addIn: "Tilføj ind", addOut: "Tilføj ud",
    whatWasItFor: "Hvad var det til?", transactionHistory: "Transaktionshistorik",
    noCashTransactionsYet: "Ingen kontanttransaktioner endnu", autoSynced: "Auto-synkroniseret",
    updated: "Opdateret!", movedToDeleted: "Flyttet til nyligt slettet",
    // Khata page
    khataTitle: "Khata — Kundekladde", khataSubtitle: "Hold styr på kreditkøb og betalinger for dine engros-kunder",
    totalReceivable: "Samlet tilgodehavende", customers: "Kunder", topDebtors: "Top skyldnere",
    noPendingBalances: "Ingen udestående beløb", searchCustomers: "Søg kunder...",
    noCustomersYet: "Ingen kunder endnu", selectCustomer: "Vælg en kunde",
    selectCustomerDesc: "Vælg en kunde fra listen for at se deres kladde",
    owed: "skyldig", overpaid: "overbetalt", settled: "Udlignet",
    recordPayment: "Registrer betaling", totalPurchased: "Samlet købt", totalPaid: "Samlet betalt",
    remaining: "Resterende", full: "Fuld", pay: "Betal",
    purchased: "Købt", paid: "Betalt", balance: "Saldo",
    noTransactionsYet: "Ingen transaktioner endnu", addFirstAbove: "— tilføj den første ovenfor",
    update: "Opdater",
    // Loan Tracker page
    loanTrackerTitle: "Lånoversigt", loanTrackerSubtitle: "Hold styr på lånte og udlånte penge med delvise betalinger",
    iOweBorrowed: "Jeg skylder (lånt)", owedToMeLent: "Skylder mig (udlånt)", netBalance: "Netto saldo",
    people: "Personer", iLent: "Jeg udlånte", iBorrowed: "Jeg lånte",
    repayment: "Tilbagebetaling", repaid: "Tilbagebetalt", lent: "Udlånt", borrowed: "Lånt",
    iOwe: "Jeg skylder", owesMe: "Skylder mig",
    selectPerson: "Vælg en person", selectPersonDesc: "Vælg nogen fra listen for at se låndetaljer",
    noPeopleYet: "Ingen personer endnu",
    // Recently Deleted page
    restore: "Gendan", deleteForever: "Slet permanent",
    noDeletedItems: "Ingen slettede elementer", waste: "Spild",
    // Personal Finance page
    personalFinance: "Personlig økonomi", trackPersonalIncome: "Hold styr på din personlige indkomst og forbrug",
    setupPersonalCategories: "Opret personlige kategorier", createCategories: "Opret kategorier",
    youHave: "Du har", youreShort: "Du mangler", spent: "brugt",
    loans: "Lån", owedToYou: "du til gode", youOwe: "du skylder", netWorth: "Formue",
    balancePlusLoans: "saldo + lån", budgetExceeded: "Budget overskredet",
    over: "over", approachingBudgetLimit: "Nærmer sig budgetgrænse",
    used: "brugt", monthlyBudget: "Månedligt budget", setBudget: "Sæt budget",
    hideBudgetSettings: "Skjul budgetindstillinger", monthlyReport: "Månedsrapport",
    hideMonthlyReport: "Skjul månedsrapport", monthlyBudgetSettings: "Månedlige budgetindstillinger",
    totalMonthlyBudget: "Samlet månedligt budget", saveBudget: "Gem budget", saved: "Gemt",
    incomeSources: "Indkomstkilder", spendingByCategory: "Forbrug efter kategori",
    whereYourMoneyGoes: "Hvor dine penge går", noSpendingData: "Ingen forbrugsdata endnu",
    noSpendingThisMonth: "Intet forbrug denne måned",
    financialSnapshot: "Økonomisk overblik", viewLoanTracker: "Se lånoversigt →",
    savingsRate: "Opsparingsrate", loanEmiPaid: "Lån/EMI betalt",
    topPeople: "Top personer", addEntry: "Tilføj post", pickCategoryOrType: "Vælg en kategori eller skriv din egen",
    greatMonth: "Fantastisk måned! Du sparede godt.", inTheGreen: "Du er i plus, fortsæt sådan!",
    overspentThisMonth: "Du overforbrugte denne måned. Gennemgå dit forbrug.",
    budgetExceededBy: "Budget overskredet med",
    // Reports page
    reportBuilder: "Rapportbygger", buildCustomReport: "Byg en tilpasset rapport og download som PDF",
    selectSections: "Vælg sektioner", overviewAlwaysIncluded: "Oversigt er altid inkluderet. Vælg hvad du vil tilføje.",
    all: "Alle", noneSelect: "Ingen", sectionsSelected: "sektioner valgt",
    includingOverview: "inkl. oversigt", downloadReportPdf: "Download rapport PDF",
    generatingPdf: "Genererer PDF...", reportsDisclaimer: "Rapporter er estimater kun til reference.",
    dailyKasserapport: "Daglig Kasserapport", kasserapport: "Kasserapport", subtotal: "Subtotal",
    totalInclVat: "Total", transactionCount: "Transaktioner", paymentBreakdown: "Betalingsoversigt",
    kasseBalance: "Kasse beholdning", printReport: "Udskriv", dailyReport: "Daglig rapport",
    expensesTotal: "Udgifter", netCash: "Netto kontant", noSalesOnDate: "Ingen salg på denne dato",
    monthlyReport: "Månedlig rapport",
    salesBreakdown: "Salgsfordeling", expenseBreakdownReport: "Udgiftsfordeling",
    inventoryReport: "Lagerrapport", khataSummary: "Khata oversigt",
    cashFlow: "Pengestrøm", wasteReport: "Spildrapport", staffRules: "Personaleregler",
    stockValue: "Lagerværdi", khataOutstanding: "Khata udestående",
    creditOwed: "Udestående kredit", lowStock: "lav beholdning",
    netProfit: "Nettoresultat",
    // Inventory extras
    loadTemplate: "Indlæs skabelon", stockItems: "Lagervarer", searchItems: "Søg varer...",
    totalItems: "Antal varer", freshItems: "Friskvarer", categories: "Kategorier",
    priced: "Prissat", stockCost: "Lageromkostning", potentialRevenue: "Potentiel omsætning",
    potentialProfit: "Potentiel fortjeneste", avgMargin: "Gns. margin",
    invested: "investeret", ifAllSold: "hvis alt sælges", itemsPriced: "varer prissat",
    filteredBy: "Filtreret efter", showAll: "Vis alle", minStock: "Min. beholdning",
    freshItem: "Friskvare", bundle: "Bundt", dozen: "Dusin",
    categoryPlaceholder: "f.eks. Drikkevarer, Mejeri",
    // Months
    january: "Januar", february: "Februar", march: "Marts", april: "April",
    may: "Maj", june: "Juni", july: "Juli", august: "August",
    september: "September", october: "Oktober", november: "November", december: "December",
  },
  np: {
    dashboard: "ड्यासबोर्ड", sales: "बिक्री", expenses: "खर्च", inventory: "स्टक",
    smartStaffing: "स्मार्ट स्टाफिङ", weatherSmart: "मौसम स्मार्ट", wasteTracker: "फोहोर ट्र्याकर", weeklyReport: "हप्ताको रिपोर्ट",
    momsVat: "भ्याट", darkMode: "डार्क मोड", lightMode: "लाइट मोड", signOut: "लग आउट",
    language: "भाषा",
    // Dashboard
    welcome: "स्वागतम", todayRevenue: "आजको आम्दानी", monthlyProfit: "मासिक नाफा",
    topExpense: "सबैभन्दा ठूलो खर्च", inventoryAlerts: "स्टक अलर्ट", snapReceipt: "रसिद खिच्नुहोस्",
    repeatYesterday: "हिजोको बिक्री दोहोर्‍याउनुहोस्", downloadPdf: "PDF रिपोर्ट डाउनलोड",
    loadingDashboard: "ड्यासबोर्ड लोड हुँदैछ...", vsYesterday: "हिजोको तुलनामा", margin: "मार्जिन",
    none: "छैन", revenueTrend: "आम्दानीको प्रवृत्ति", expenseBreakdown: "खर्चको विवरण",
    noRevenueData: "अहिलेसम्म आम्दानी डाटा छैन", noExpenseData: "अहिलेसम्म खर्च डाटा छैन",
    recentReceipts: "हालका रसिदहरू", dailyGoal: "दैनिक लक्ष्य", monthlyGoal: "मासिक लक्ष्य", reached: "पुग्यो!",
    setDailyGoal: "दैनिक आम्दानीको लक्ष्य राख्नुहोस्", trackProgress: "प्रगति ट्र्याक गर्न लक्ष्य राख्नुहोस्",
    setGoal: "लक्ष्य राख्नुहोस्", editGoal: "लक्ष्य सम्पादन", save: "सेभ", cancel: "रद्द",
    yesterdayCopied: "हिजोको बिक्री आजमा कपी भयो!", noYesterdaySale: "हिजोको बिक्री भेटिएन",
    // Sales
    salesTracker: "बिक्री ट्र्याकर", logSale: "आजको बिक्री राख्नुहोस्",
    tapAmount: "रकम छान्नुहोस् वा आफ्नो टाइप गर्नुहोस्", customAmount: "आफ्नो रकम...", log: "राख्नुहोस्",
    recentSales: "हालका बिक्रीहरू", date: "मिति", amount: "रकम", payment: "भुक्तानी",
    noSalesYet: "अहिलेसम्म बिक्री छैन — माथि रकम थिच्नुहोस्!",
    importCsv: "CSV बाट आयात", csvColumns: "स्तम्भहरू: date, amount, payment_method (ऐच्छिक)",
    uploading: "अपलोड हुँदैछ...", chooseFile: "फाइल छान्नुहोस्",
    salesImported: "बिक्री आयात भयो", rowsSkipped: "पङ्क्ति छोडियो",
    // Expenses
    expenseTracker: "खर्च ट्र्याकर", addExpense: "खर्च थप्नुहोस्",
    pickCategory: "कोटि छान्नुहोस्, विवरण लेख्नुहोस्, रकम थिच्नुहोस्",
    whatWasIt: "के थियो? (जस्तै: गोलभेडा, बिजुलीको बिल)", add: "थप्नुहोस्",
    recentExpenses: "हालका खर्चहरू", description: "विवरण",
    noExpensesYet: "अहिलेसम्म खर्च छैन — कोटि छानेर माथि थप्नुहोस्!",
    firstTimeSetup: "पहिलो पटक? एक थिचाइमा सामान्य कोटिहरू सेटअप गर्नुहोस्",
    setupCategories: "कोटिहरू सेटअप",
    // Inventory
    inventoryMonitor: "स्टक मनिटर", lowStockAlerts: "कम स्टक अलर्ट", itemsBelowMinStock: "न्यूनतम स्टकभन्दा कम",
    addItem: "सामान थप्नुहोस्", itemName: "सामानको नाम", quantity: "परिमाण", unit: "इकाई",
    costPerUnit: "प्रति इकाई मूल्य", threshold: "न्यूनतम सीमा",
    pieces: "थान", kg: "केजी", liters: "लिटर", boxes: "बाकस",
    noInventoryYet: "अहिलेसम्म स्टकमा सामान छैन",
    // Staffing
    analyzingPatterns: "बिक्री ढाँचा विश्लेषण हुँदैछ...", notEnoughData: "अहिलेसम्म पर्याप्त बिक्री डाटा छैन",
    logMoreSales: "पूर्वानुमानको लागि कम्तिमा केही हप्ताको बिक्री राख्नुहोस्",
    slowDaysAhead: "सुस्त दिनहरू आउँदैछन्", reduceStaff: "कर्मचारी घटाउनुहोस्, कम तयारी गर्नुहोस्",
    normalDays: "सामान्य दिनहरू", standardStaffing: "सामान्य स्टाफिङ",
    busyDaysAhead: "व्यस्त दिनहरू आउँदैछन्", extraStaff: "थप कर्मचारी चाहिन्छ",
    revenueForecast: "आम्दानी पूर्वानुमान र सिफारिस स्टाफ", salesPatterns: "तपाईंको बिक्री ढाँचा",
    predictedRevenue: "अनुमानित आम्दानी", day: "दिन", level: "स्तर",
    staffNeeded: "चाहिने कर्मचारी", confidence: "विश्वसनीयता", staffingRules: "स्टाफिङ नियमहरू",
    staffingRulesDesc: "विभिन्न आम्दानी स्तरमा कति कर्मचारी चाहिन्छ भनेर तोक्नुहोस्।",
    addRule: "नियम थप्नुहोस्", remove: "हटाउनुहोस्", staff: "कर्मचारी",
    next7days: "अर्को ७ दिन", next14days: "अर्को १४ दिन", next30days: "अर्को ३० दिन",
    totalStaffNeeded: "कुल चाहिने कर्मचारी", basedOnPatterns: "अनुमानित आम्दानी ढाँचामा आधारित",
    minRevenue: "न्यूनतम आम्दानी", maxRevenue: "अधिकतम आम्दानी",
    slow: "सुस्त", normal: "सामान्य", busy: "व्यस्त",
    // Waste
    logWaste: "फोहोर राख्नुहोस्", trackWaste: "के फालियो ट्र्याक गर्नुहोस्",
    wasteLogged: "फोहोर रेकर्ड भयो!", monthlyWasteCost: "मासिक फोहोर खर्च",
    itemsWasted: "फालिएका सामानहरू", noDataYet: "अहिलेसम्म डाटा छैन",
    whatWasWasted: "के फालियो? (जस्तै: कुखुराको मासु)", qty: "परिमाण",
    estimatedCost: "अनुमानित मूल्य", customCost: "आफ्नो मूल्य...",
    recentWaste: "हालको फोहोर", item: "सामान", reason: "कारण", cost: "मूल्य",
    noWasteYet: "अहिलेसम्म फोहोर रेकर्ड छैन",
    expired: "म्याद सकियो", overcooked: "बढी पाकेको", damaged: "बिग्रेको", other: "अन्य",
    // Weekly Report
    weeklySalesReport: "हप्ताको बिक्री रिपोर्ट", dailyAvg: "दैनिक औसत",
    daysRecorded: "रेकर्ड गरिएका दिन", bestDay: "सबैभन्दा राम्रो दिन", slowestDay: "सबैभन्दा सुस्त दिन",
    revenue: "आम्दानी", vsLastWeek: "गत हप्ताको तुलनामा",
    loadingReport: "रिपोर्ट लोड हुँदैछ...", noSalesData: "अहिलेसम्म बिक्री डाटा उपलब्ध छैन।",
    // VAT
    vatReport: "कर रिपोर्ट", salesSection: "बिक्री",
    salesInclVat: "भ्याट सहित बिक्री", salesExclVat: "भ्याट बिना बिक्री",
    outputVat: "आउटपुट भ्याट", expensesSection: "खर्च",
    expensesInclVat: "भ्याट सहित खर्च", expensesExclVat: "भ्याट बिना खर्च",
    inputVat: "इनपुट भ्याट", vatPayable: "तिर्नुपर्ने भ्याट",
    payableToSkat: "कर कार्यालयलाई तिर्नुपर्ने रकम", refundFromSkat: "कर कार्यालयबाट फिर्ता हुने रकम",
    loadingVat: "कर रिपोर्ट लोड हुँदैछ...", vatError: "कर रिपोर्ट लोड गर्न सकिएन।",
    // Receipt
    uploadReceipt: "रसिदको फोटो अपलोड गर्नुहोस्", takePhoto: "फोटो खिच्नुहोस्",
    photoOrGallery: "फोटो खिच्नुहोस् वा ग्यालरीबाट छान्नुहोस्", scanningReceipt: "रसिद स्क्यान हुँदैछ...",
    detectedAmount: "पत्ता लागेको रकम", couldntRead: "रकम पढ्न सकिएन — तल आफैं टाइप गर्नुहोस्",
    ocrNotAvailable: "OCR उपलब्ध छैन — रकम आफैं टाइप गर्नुहोस्",
    enterTotal: "कुल रकम लेख्नुहोस्...", confirmLog: "पुष्टि गरी बिक्री राख्नुहोस्",
    saleLoggedReceipt: "रसिदबाट बिक्री रेकर्ड भयो!",
    // Quick Add
    quickEntry: "छिटो एन्ट्री", logSaleTab: "बिक्री राख्नुहोस्", addExpenseTab: "खर्च थप्नुहोस्",
    quickAmount: "छिटो रकम", orTypeAmount: "वा रकम टाइप गर्नुहोस्...",
    category: "कोटि", addCategoriesFirst: "पहिले खर्च पेजमा कोटिहरू थप्नुहोस्",
    whatForExpense: "के को लागि थियो? (जस्तै: गोलभेडा)",
    saleLogged: "बिक्री रेकर्ड भयो!", expenseAdded: "खर्च थपियो!",
    // Forecast
    revenueForecastTitle: "आम्दानी पूर्वानुमान", nextDays: "अर्को ७ दिन",
    predictedTotal: "अनुमानित जम्मा", avgDaily: "औसत/दिन",
    trendUp: "बढ्दो", trendDown: "घट्दो", trendStable: "स्थिर",
    forecastConfidence: "विश्वसनीयता", noForecastData: "पूर्वानुमानको लागि थप बिक्री डाटा चाहिन्छ",
    predicted: "अनुमानित", actual: "वास्तविक",
    // Feedback
    feedback: "प्रतिक्रिया", sendFeedback: "प्रतिक्रिया पठाउनुहोस्", yourFeedback: "तपाईंको प्रतिक्रिया",
    feedbackSent: "प्रतिक्रियाको लागि धन्यवाद!", rateExperience: "आफ्नो अनुभव मूल्याङ्कन गर्नुहोस्",
    feedbackMessage: "तपाईंको विचार लेख्नुहोस्...", bugReport: "बग रिपोर्ट",
    featureRequest: "फिचर अनुरोध", generalFeedback: "सामान्य प्रतिक्रिया",
    complaint: "उजुरी", praise: "प्रशंसा", noFeedbackYet: "अहिलेसम्म प्रतिक्रिया छैन",
    stars: "तारा",
    // Payment methods
    cash: "नगद", card: "कार्ड", mobilepay: "MobilePay", mixed: "मिश्रित",
    dankort: "Dankort", bankTransfer: "बैंक ट्रान्सफर",
    // Quick Sale
    quickSale: "छिटो बिक्री",
    // Time periods
    today: "आज", thisWeek: "यो हप्ता", thisMonth: "यो महिना", last30Days: "गत ३० दिन",
    // Layout / Nav
    businessMode: "व्यापार मोड", personalMode: "व्यक्तिगत मोड",
    reports: "रिपोर्टहरू", khata: "खाता", loanTracker: "ऋण ट्र्याकर",
    // Common actions
    delete: "मेट्नुहोस्", edit: "सम्पादन", or: "वा",
    search: "खोज्नुहोस्...", exportCsv: "CSV निर्यात", clear: "खाली गर्नुहोस्",
    noData: "डाटा छैन", loading: "लोड हुँदैछ...",
    // QuickAdd personal
    income: "आम्दानी", expense: "खर्च", incomeSource: "आम्दानीको स्रोत",
    spendingCategory: "खर्चको कोटि", amountReceived: "प्राप्त रकम",
    amountSpent: "खर्च गरिएको रकम", notesOptional: "टिप्पणी (ऐच्छिक)",
    logIncome: "आम्दानी राख्नुहोस्", logExpense: "खर्च राख्नुहोस्",
    incomeLogged: "आम्दानी रेकर्ड भयो!", expenseLogged: "खर्च रेकर्ड भयो!",
    noIncomeCatsYet: "अहिलेसम्म आम्दानी कोटि छैन", noSpendCatsYet: "अहिलेसम्म खर्च कोटि छैन",
    // Dashboard extras
    todaysProfit: "आजको नाफा", thisWeekRevenue: "यो हप्ताको आम्दानी",
    thisWeekProfit: "यो हप्ताको नाफा", thisMonthRevenue: "यो महिनाको आम्दानी",
    thisMonthProfit: "यो महिनाको नाफा", last30Revenue: "गत ३० दिनको आम्दानी",
    last30Profit: "गत ३० दिनको नाफा",
    profitability: "नाफा", consistency: "नियमितता", growth: "वृद्धि",
    costControl: "खर्च नियन्त्रण", activity: "सक्रियता",
    excellent: "उत्कृष्ट", good: "राम्रो", needsWork: "सुधार चाहिन्छ", critical: "गम्भीर",
    businessHealth: "व्यापार स्वास्थ्य", onTrack: "सही बाटोमा", average: "औसत",
    needsAttention: "ध्यान चाहिन्छ", khataReceivable: "खाता लिनुपर्ने",
    outstandingCredit: "बाँकी रकम", daysActive: "दिन सक्रिय",
    ofRevenue: "आम्दानीको", activeToday: "आज सक्रिय", noSalesToday: "आज बिक्री छैन",
    notProfitableYet: "अहिलेसम्म नाफा छैन",
    // Inventory extras
    general: "सामान्य", itemAdded: "सामान थपियो!", itemUpdated: "सामान अपडेट भयो!",
    stockAdded: "स्टक थपियो", stockRemoved: "स्टक घटाइयो", itemDeleted: "सामान मेटियो",
    // Expenses extras
    backdatedEntry: "पुरानो मितिको एन्ट्री", personalExpense: "व्यक्तिगत खर्च",
    businessExpense: "व्यापारिक खर्च", excludedFromReports: "रिपोर्ट र भ्याटबाट बाहिर",
    typeCustomCategory: "आफ्नो कोटि लेख्नुहोस्...", moveToTrash: "रद्दीमा सार्नुहोस्",
    actions: "कार्य", notes: "टिप्पणी",
    // Cash Book
    cashBook: "खाता",
    // Contact
    contact: "सम्पर्क",
    // Recently Deleted
    recentlyDeleted: "हालै मेटाइएको",
    // Profile
    profile: "प्रोफाइल",
    // Cash Book page
    cashBalance: "नगद मौज्दात", totalCashIn: "कुल नगद आउने", totalCashOut: "कुल नगद जाने",
    cashIn: "नगद आउने", cashOut: "नगद जाने", addIn: "आउने थप्नुहोस्", addOut: "जाने थप्नुहोस्",
    whatWasItFor: "के को लागि थियो?", transactionHistory: "कारोबार इतिहास",
    noCashTransactionsYet: "अहिलेसम्म नगद कारोबार छैन", autoSynced: "स्वचालित",
    updated: "अपडेट भयो!", movedToDeleted: "हालै मेटाइएकोमा सारियो",
    // Khata page
    khataTitle: "खाता — ग्राहक खाता", khataSubtitle: "तपाईंका थोक ग्राहकहरूको उधारो र भुक्तानी ट्र्याक गर्नुहोस्",
    totalReceivable: "कुल लिनुपर्ने", customers: "ग्राहकहरू", topDebtors: "शीर्ष ऋणीहरू",
    noPendingBalances: "बाँकी रकम छैन", searchCustomers: "ग्राहक खोज्नुहोस्...",
    noCustomersYet: "अहिलेसम्म ग्राहक छैन", selectCustomer: "ग्राहक छान्नुहोस्",
    selectCustomerDesc: "उनीहरूको खाता हेर्न सूचीबाट ग्राहक छान्नुहोस्",
    owed: "बाँकी", overpaid: "बढी तिरेको", settled: "चुक्ता",
    recordPayment: "भुक्तानी राख्नुहोस्", totalPurchased: "कुल खरिद", totalPaid: "कुल तिरेको",
    remaining: "बाँकी", full: "पूरा", pay: "तिर्नुहोस्",
    purchased: "खरिद", paid: "तिरेको", balance: "मौज्दात",
    noTransactionsYet: "अहिलेसम्म कारोबार छैन", addFirstAbove: "— माथि पहिलो थप्नुहोस्",
    update: "अपडेट",
    // Loan Tracker page
    loanTrackerTitle: "ऋण ट्र्याकर", loanTrackerSubtitle: "उधारो लिएको र दिएको पैसा आंशिक भुक्तानीसहित ट्र्याक गर्नुहोस्",
    iOweBorrowed: "मैले तिर्नुपर्ने (सापटी)", owedToMeLent: "मलाई तिर्नुपर्ने (ऋण)", netBalance: "खुद मौज्दात",
    people: "व्यक्तिहरू", iLent: "मैले दिएँ", iBorrowed: "मैले लिएँ",
    repayment: "फिर्ता", repaid: "फिर्ता गरियो", lent: "दिएको", borrowed: "लिएको",
    iOwe: "मैले तिर्नुपर्ने", owesMe: "मलाई तिर्नुपर्ने",
    selectPerson: "व्यक्ति छान्नुहोस्", selectPersonDesc: "ऋण विवरण हेर्न सूचीबाट कसैलाई छान्नुहोस्",
    noPeopleYet: "अहिलेसम्म व्यक्ति छैन",
    // Recently Deleted page
    restore: "पुनर्स्थापना", deleteForever: "सधैंको लागि मेट्नुहोस्",
    noDeletedItems: "मेटिएका सामानहरू छैनन्", waste: "फोहोर",
    // Personal Finance page
    personalFinance: "व्यक्तिगत वित्त", trackPersonalIncome: "तपाईंको व्यक्तिगत आम्दानी र खर्च ट्र्याक गर्नुहोस्",
    setupPersonalCategories: "व्यक्तिगत कोटिहरू सेटअप गर्नुहोस्", createCategories: "कोटिहरू बनाउनुहोस्",
    youHave: "तपाईंसँग छ", youreShort: "तपाईंलाई कम छ", spent: "खर्च",
    loans: "ऋण", owedToYou: "तपाईंलाई तिर्नुपर्ने", youOwe: "तपाईंले तिर्नुपर्ने", netWorth: "कुल सम्पत्ति",
    balancePlusLoans: "मौज्दात + ऋण", budgetExceeded: "बजेट नाघ्यो",
    over: "बढी", approachingBudgetLimit: "बजेट सीमा नजिक",
    used: "प्रयोग", monthlyBudget: "मासिक बजेट", setBudget: "बजेट राख्नुहोस्",
    hideBudgetSettings: "बजेट सेटिङ लुकाउनुहोस्", monthlyReport: "मासिक रिपोर्ट",
    hideMonthlyReport: "मासिक रिपोर्ट लुकाउनुहोस्", monthlyBudgetSettings: "मासिक बजेट सेटिङ",
    totalMonthlyBudget: "कुल मासिक बजेट", saveBudget: "बजेट सेभ", saved: "सेभ भयो",
    incomeSources: "आम्दानीका स्रोतहरू", spendingByCategory: "कोटि अनुसार खर्च",
    whereYourMoneyGoes: "तपाईंको पैसा कहाँ जान्छ", noSpendingData: "अहिलेसम्म खर्च डाटा छैन",
    noSpendingThisMonth: "यो महिना खर्च छैन",
    financialSnapshot: "आर्थिक तस्वीर", viewLoanTracker: "ऋण ट्र्याकर हेर्नुहोस् →",
    savingsRate: "बचत दर", loanEmiPaid: "ऋण/EMI तिरेको",
    topPeople: "शीर्ष व्यक्तिहरू", addEntry: "एन्ट्री थप्नुहोस्", pickCategoryOrType: "कोटि छान्नुहोस् वा आफ्नो लेख्नुहोस्",
    greatMonth: "राम्रो महिना! तपाईंले राम्रो बचत गर्नुभयो।", inTheGreen: "तपाईं फाइदामा हुनुहुन्छ, जारी राख्नुहोस्!",
    overspentThisMonth: "यो महिना बढी खर्च भयो। आफ्नो खर्च समीक्षा गर्नुहोस्।",
    budgetExceededBy: "बजेट नाघेको रकम",
    // Reports page
    reportBuilder: "रिपोर्ट बिल्डर", buildCustomReport: "आफ्नो रिपोर्ट बनाएर PDF डाउनलोड गर्नुहोस्",
    selectSections: "खण्डहरू छान्नुहोस्", overviewAlwaysIncluded: "सारांश सधैं समावेश हुन्छ। अरू के थप्ने छान्नुहोस्।",
    all: "सबै", noneSelect: "कुनै पनि होइन", sectionsSelected: "खण्डहरू छानिएको",
    includingOverview: "सारांश सहित", downloadReportPdf: "रिपोर्ट PDF डाउनलोड",
    generatingPdf: "PDF बनाउँदै...", reportsDisclaimer: "रिपोर्टहरू अनुमान मात्र हुन्।",
    dailyKasserapport: "दैनिक क्यासरिपोर्ट", kasserapport: "क्यासरिपोर्ट", subtotal: "उपकुल",
    totalInclVat: "जम्मा", transactionCount: "कारोबारहरू", paymentBreakdown: "भुक्तानी विवरण",
    kasseBalance: "क्यास ब्यालेन्स", printReport: "प्रिन्ट", dailyReport: "दैनिक रिपोर्ट",
    expensesTotal: "खर्चहरू", netCash: "शुद्ध नगद", noSalesOnDate: "यो मितिमा कुनै बिक्री छैन",
    monthlyReport: "मासिक रिपोर्ट",
    salesBreakdown: "बिक्री विवरण", expenseBreakdownReport: "खर्च विवरण",
    inventoryReport: "स्टक रिपोर्ट", khataSummary: "खाता सारांश",
    cashFlow: "नगद प्रवाह", wasteReport: "फोहोर रिपोर्ट", staffRules: "कर्मचारी नियम",
    stockValue: "स्टक मूल्य", khataOutstanding: "खाता बाँकी",
    creditOwed: "बाँकी उधारो", lowStock: "कम स्टक",
    netProfit: "खुद नाफा",
    // Inventory extras
    loadTemplate: "टेम्प्लेट लोड", stockItems: "स्टक सामानहरू", searchItems: "सामान खोज्नुहोस्...",
    totalItems: "कुल सामान", freshItems: "ताजा सामान", categories: "कोटिहरू",
    priced: "मूल्य राखिएको", stockCost: "स्टक लागत", potentialRevenue: "सम्भावित आम्दानी",
    potentialProfit: "सम्भावित नाफा", avgMargin: "औसत मार्जिन",
    invested: "लगानी", ifAllSold: "सबै बिक्री भएमा", itemsPriced: "सामानहरू मूल्य राखिएको",
    filteredBy: "फिल्टर गरिएको", showAll: "सबै देखाउनुहोस्", minStock: "न्यूनतम स्टक",
    freshItem: "ताजा सामान", bundle: "बन्डल", dozen: "दर्जन",
    categoryPlaceholder: "जस्तै: पेय पदार्थ, दूध",
    // Months
    january: "जनवरी", february: "फेब्रुअरी", march: "मार्च", april: "अप्रिल",
    may: "मे", june: "जुन", july: "जुलाई", august: "अगस्ट",
    september: "सेप्टेम्बर", october: "अक्टोबर", november: "नोभेम्बर", december: "डिसेम्बर",
  },
};

const LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "da", label: "Dansk", flag: "🇩🇰" },
  { code: "np", label: "नेपाली", flag: "🇳🇵" },
];

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem("lang") || "en");

  const setLang = (code) => {
    setLangState(code);
    localStorage.setItem("lang", code);
  };

  // Keep toggleLang for backward compat — cycles through all languages
  const toggleLang = () => {
    const codes = LANGUAGES.map((l) => l.code);
    const idx = codes.indexOf(lang);
    const next = codes[(idx + 1) % codes.length];
    setLang(next);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
