"""
Web Push (VAPID) — subscribe / unsubscribe / public-key / test (Task #72).

Endpoints (all mounted under /api/push):

  POST /subscribe         Auth-gated. Body: {endpoint, keys: {p256dh, auth},
                          user_agent?}. Upsert one row per (user, endpoint).
                          Re-subscribing the same device returns 200 with the
                          existing row's id (no duplicate).
  POST /unsubscribe       Auth-gated. Body: {endpoint}. Hard-deletes the
                          caller's row for that endpoint. Cross-tenant
                          requests (someone else's endpoint) silently no-op
                          (404 leaks "endpoint exists for another user").
  GET  /vapid-public-key  PUBLIC. Returns the raw VAPID public key as
                          text/plain so the frontend can pass it to
                          PushManager.subscribe(). 503 when VAPID is not
                          configured in env (PR previews, CI).
  POST /test              Auth-gated, 5/hour. Fans a "BonBox: push works!"
                          notification out to all the caller's subscriptions.
                          Writes a push.test.sent audit row.

Privacy posture (BonBox handles GDPR-regulated data):
  • Endpoint URLs are PII. They are NEVER returned to the client by any
    endpoint (subscribe returns only the row id + masked tail). Error
    logs use the redacted form from push_sender._redact_endpoint.
  • Audit rows for /test record counts only — not endpoints.

Multi-layer defense (the BonBox standard stack):
  L1 auth          — get_current_user dep on every mutation
  L2 tenant scope  — every query filters by user.id
  L3 input bounds  — Pydantic schemas on body; field length caps
  L4 rate limit    — /test is 5/hour per IP (SlowAPI)
  L5 audit trail   — push.subscribed, push.unsubscribed, push.test.sent
  L6 503 graceful  — endpoints return 503 (not 500) when VAPID_*
                     env vars are missing so the rest of the app stays up
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from slowapi import Limiter
from slowapi.util import get_remote_address
from app.utils.client_ip import client_ip
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.models.push_subscription import PushSubscription
from app.models.user import User
from app.services import audit_service
from app.services.auth import get_current_user
from app.services.push_sender import (
    _vapid_configured,
    send_to_subscription,
)

logger = logging.getLogger(__name__)

router = APIRouter()

# Per-IP rate limiter for the manual /test endpoint. Prevents an
# authenticated user from fanning push spam to themselves (or — more
# importantly — using us as a free push relay if there's ever a bug
# in the multi-tenant scope).
limiter = Limiter(key_func=client_ip)


# ─── Schemas ──────────────────────────────────────────────────────────


class _Keys(BaseModel):
    p256dh: str = Field(..., min_length=10, max_length=200)
    auth: str = Field(..., min_length=4, max_length=64)


class SubscribeIn(BaseModel):
    endpoint: str = Field(..., min_length=10, max_length=2000)
    keys: _Keys
    user_agent: str | None = Field(default=None, max_length=500)


class SubscribeOut(BaseModel):
    id: str
    created: bool
    # Echo back the masked tail so the UI can confirm "this device is
    # subscribed" without exposing the raw endpoint to the page.
    endpoint_suffix: str


class UnsubscribeIn(BaseModel):
    endpoint: str = Field(..., min_length=10, max_length=2000)


class TestOut(BaseModel):
    attempted: int
    sent: int
    removed: int


# ─── Helpers ──────────────────────────────────────────────────────────


def _endpoint_suffix(endpoint: str) -> str:
    """Last 8 visible chars of the endpoint. Safe to echo back to the
    client because the endpoint is generated by the push provider with
    enough entropy that 8 chars don't help anyone guess it."""
    if not endpoint:
        return ""
    return endpoint[-8:]


def _client_ip(request: Request | None) -> str | None:
    try:
        return request.client.host if request and request.client else None
    except Exception:  # noqa: BLE001
        return None


def _require_vapid_configured() -> None:
    """Translate "no VAPID env" into a clean 503. Without this the
    /subscribe call would succeed and only the actual send would fail —
    leaving stale rows around that no cron can ever drain."""
    if not _vapid_configured():
        raise HTTPException(
            status_code=503,
            detail="push_disabled: VAPID keys not configured",
        )


# ─── Endpoints ────────────────────────────────────────────────────────


@router.get("/vapid-public-key", response_class=PlainTextResponse)
def get_vapid_public_key():
    """Public endpoint — frontend needs this BEFORE it can call
    PushManager.subscribe(). Cached by the browser; rotated only at
    key rollover (rare). text/plain so the frontend can read it with
    `await res.text()` without JSON parsing."""
    if not _vapid_configured():
        raise HTTPException(
            status_code=503,
            detail="push_disabled: VAPID keys not configured",
        )
    pub = settings.VAPID_PUBLIC_KEY or ""
    return PlainTextResponse(pub.strip())


@router.post("/subscribe", response_model=SubscribeOut)
def subscribe(
    data: SubscribeIn,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Idempotent upsert. Body:
        {endpoint, keys: {p256dh, auth}, user_agent}
    Returns the row id + a masked tail. 200 OK in both create and
    update cases — frontend doesn't need to distinguish.
    """
    _require_vapid_configured()

    # Look for an existing row for THIS user + endpoint. Critical:
    # filter on user_id AND endpoint together. The endpoint column is
    # globally unique already (one row per endpoint, ever), but
    # filtering by user_id stops a malicious client from "stealing" a
    # different user's endpoint and learning it exists.
    existing = (
        db.query(PushSubscription)
        .filter(
            PushSubscription.user_id == user.id,
            PushSubscription.endpoint == data.endpoint,
        )
        .first()
    )

    if existing is not None:
        # Update the keys + user_agent in case the device renewed its
        # subscription. fail_count resets — a re-subscribe means the
        # device is alive.
        existing.p256dh = data.keys.p256dh
        existing.auth = data.keys.auth
        if data.user_agent:
            existing.user_agent = data.user_agent[:500]
        existing.fail_count = 0
        try:
            db.commit()
        except Exception as e:  # noqa: BLE001
            db.rollback()
            logger.exception("push.subscribe: upsert commit failed: %s", e)
            raise HTTPException(status_code=500, detail="db_error")
        return SubscribeOut(
            id=str(existing.id),
            created=False,
            endpoint_suffix=_endpoint_suffix(existing.endpoint),
        )

    # Brand new row.
    row = PushSubscription(
        user_id=user.id,
        endpoint=data.endpoint,
        p256dh=data.keys.p256dh,
        auth=data.keys.auth,
        user_agent=(data.user_agent[:500] if data.user_agent else None),
        fail_count=0,
    )
    db.add(row)
    try:
        # Audit before commit so a failed commit rolls the audit row
        # back too (avoids "we logged a subscribe that never happened").
        audit_service.record(
            db, user, "push.subscribed", "push_subscription",
            entity_id=row.id,
            after={"endpoint_suffix": _endpoint_suffix(data.endpoint)},
            ip_address=_client_ip(request),
        )
        db.commit()
    except Exception as e:  # noqa: BLE001
        db.rollback()
        # Rare race: two concurrent /subscribe with the same endpoint
        # under different users → the global UNIQUE on endpoint kicks
        # in. Try once more as an upsert (probably the same client
        # double-tapped). Otherwise surface a clean error.
        existing = (
            db.query(PushSubscription)
            .filter(PushSubscription.endpoint == data.endpoint)
            .first()
        )
        if existing and existing.user_id == user.id:
            return SubscribeOut(
                id=str(existing.id),
                created=False,
                endpoint_suffix=_endpoint_suffix(existing.endpoint),
            )
        logger.exception("push.subscribe: insert failed: %s", e)
        raise HTTPException(status_code=409, detail="conflict")

    return SubscribeOut(
        id=str(row.id),
        created=True,
        endpoint_suffix=_endpoint_suffix(row.endpoint),
    )


@router.post("/unsubscribe")
def unsubscribe(
    data: UnsubscribeIn,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Hard-delete the row for (user_id, endpoint). Returns 200 in
    both delete-happened and nothing-to-delete cases — the frontend
    doesn't need to distinguish, and a 404 would leak "this endpoint
    belongs to another user"."""
    row = (
        db.query(PushSubscription)
        .filter(
            PushSubscription.user_id == user.id,
            PushSubscription.endpoint == data.endpoint,
        )
        .first()
    )
    deleted = False
    if row is not None:
        suffix = _endpoint_suffix(row.endpoint)
        db.delete(row)
        try:
            audit_service.record(
                db, user, "push.unsubscribed", "push_subscription",
                entity_id=row.id,
                before={"endpoint_suffix": suffix},
                ip_address=_client_ip(request),
            )
            db.commit()
            deleted = True
        except Exception as e:  # noqa: BLE001
            db.rollback()
            logger.exception("push.unsubscribe: commit failed: %s", e)
            raise HTTPException(status_code=500, detail="db_error")
    return {"ok": True, "deleted": deleted}


@router.post("/test", response_model=TestOut)
@limiter.limit("5/hour")
def send_test_push(
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Fan a "BonBox: push works!" notification out to every active
    subscription belonging to the caller. 5/hour rate limit per IP."""
    _require_vapid_configured()

    subs = (
        db.query(PushSubscription)
        .filter(PushSubscription.user_id == user.id)
        .all()
    )

    payload = {
        "title": "BonBox",
        "body": "Push works — you'll get tomorrow's morning brief here.",
        "tag": "bonbox-test",
        "data": {"url": "/"},
    }

    attempted = 0
    sent = 0
    removed = 0
    for sub in subs:
        attempted += 1
        result = send_to_subscription(sub, payload)
        if result.get("ok"):
            sent += 1
        if result.get("removed"):
            removed += 1
            try:
                db.delete(sub)
            except Exception:  # noqa: BLE001
                pass

    try:
        audit_service.record(
            db, user, "push.test.sent", "push_subscription",
            after={"attempted": attempted, "sent": sent, "removed": removed},
            ip_address=_client_ip(request),
        )
        db.commit()
    except Exception as e:  # noqa: BLE001
        db.rollback()
        logger.warning("push.test: audit commit failed: %s", e)

    return TestOut(attempted=attempted, sent=sent, removed=removed)
