"""Daily close range export — multi-day PDF + CSV for accountant handoff.

Distinct from the per-close PDF (services/kasserapport_pdf.py) which
makes one polished receipt per closing day. This module aggregates a
DATE RANGE into a single document, with totals + averages so the
accountant can review a week / month / quarter at a glance.

Two formats:
  • PDF — table with one row per close, totals row at bottom, MOMS
    summary, perfect for SKAT / Bogføringsloven §10 month-end
    handoff.
  • CSV — same data tabular, semicolon-delimited + UTF-8 BOM so
    Danish-locale Excel opens it cleanly.

Inputs are pre-filtered DailyClose ORM rows (date+user already
narrowed by the router); this service only formats.
"""
from __future__ import annotations

import csv
import io
from datetime import date

from app.models.daily_close import DailyClose, decode_breakdown


# ─── CSV ──────────────────────────────────────────────────────────────

_CSV_COLUMNS = [
    "date", "branch_id", "status",
    "revenue_total", "revenue_ex_moms", "moms_total", "moms_mode",
    "payment_total", "cash_expected", "cash_counted", "cash_difference",
    "tips_total", "tips_staff_count", "tips_per_person",
    "revenue_breakdown",   # encoded "food:12400|drinks:5800"
    "payment_breakdown",   # encoded "cash:4200|card:13500"
    "closed_by", "closed_at",
    "unlock_reason", "unlocked_by", "unlocked_at",
    "notes", "receipt_photo",
]


def _opt(v):
    """Format an optional float as fixed 2-decimal or empty string."""
    if v is None:
        return ""
    return f"{float(v):.2f}"


def closes_to_csv_bytes(closes: list[DailyClose]) -> bytes:
    """Serialize a list of DailyClose to CSV. UTF-8 BOM + semicolon
    delimiter so Danish Excel opens it cleanly with Æ/Ø/Å intact."""
    buf = io.StringIO()
    buf.write("﻿")
    writer = csv.writer(buf, delimiter=";")
    writer.writerow(_CSV_COLUMNS)
    for c in closes:
        writer.writerow([
            c.date.isoformat() if c.date else "",
            str(c.branch_id) if c.branch_id else "",
            getattr(c, "status", "") or "",
            _opt(c.revenue_total),
            _opt(c.revenue_ex_moms),
            _opt(c.moms_total),
            getattr(c, "moms_mode", "") or "",
            _opt(c.payment_total),
            _opt(c.cash_expected),
            _opt(c.cash_counted),
            _opt(c.cash_difference),
            _opt(c.tips_total),
            c.tips_staff_count if c.tips_staff_count is not None else "",
            _opt(c.tips_per_person),
            c.revenue_categories or "",
            c.payment_categories or "",
            c.closed_by or "",
            c.closed_at.isoformat() if c.closed_at else "",
            getattr(c, "unlock_reason", "") or "",
            getattr(c, "unlocked_by", "") or "",
            (c.unlocked_at.isoformat() if getattr(c, "unlocked_at", None) else ""),
            c.notes or "",
            getattr(c, "receipt_photo", "") or "",
        ])
    return buf.getvalue().encode("utf-8")


# ─── PDF ──────────────────────────────────────────────────────────────

def build_daily_close_range_pdf(
    closes: list[DailyClose],
    *,
    from_date: date,
    to_date: date,
    business_name: str = "Daily Close Report",
    currency: str = "DKK",
) -> bytes:
    """Build a multi-day daily-close PDF report.

    Layout:
      • Header: business name + date range + count
      • Summary row: total revenue, MOMS, tips, average per close
      • Table: one row per close (date, revenue, MOMS, payment total,
               cash diff, tips)
      • Totals row at the bottom
      • Footer: 'Generated by BonBox · Bogføringsloven §10 retention'
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    )

    # Sort ascending so the report reads chronologically.
    closes_sorted = sorted(closes, key=lambda c: c.date or date.min)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),    # landscape — more table real estate
        leftMargin=18*mm, rightMargin=18*mm,
        topMargin=18*mm, bottomMargin=15*mm,
        title=f"Daily Close — {business_name}",
        author="BonBox",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"], fontName="Helvetica-Bold",
        fontSize=18, leading=22, spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontName="Helvetica",
        fontSize=10, textColor=colors.grey, leading=14, spaceAfter=10,
    )
    note_style = ParagraphStyle(
        "Note", parent=styles["Normal"], fontName="Helvetica",
        fontSize=9, textColor=colors.grey, leading=12,
    )

    story = []

    # ─── Header ──────────────────────────────────────────────────────
    story.append(Paragraph(f"📋 Daily Close — {business_name}", title_style))
    n = len(closes_sorted)
    span_days = (to_date - from_date).days + 1 if to_date >= from_date else 1
    story.append(Paragraph(
        f"{from_date.strftime('%d %b %Y')} → {to_date.strftime('%d %b %Y')}  ·  "
        f"{n} close{'s' if n != 1 else ''} across {span_days} day{'s' if span_days != 1 else ''}  ·  "
        f"All amounts in {currency}",
        subtitle_style,
    ))

    if not closes_sorted:
        story.append(Paragraph(
            "No daily closes found in this range.", note_style,
        ))
        story.append(Spacer(1, 12))
        story.append(Paragraph(
            "Generated by BonBox · Bogføringsloven §10 retention",
            note_style,
        ))
        doc.build(story)
        return buf.getvalue()

    # ─── Summary band ────────────────────────────────────────────────
    total_revenue = sum(float(c.revenue_total or 0) for c in closes_sorted)
    total_moms = sum(float(c.moms_total or 0) for c in closes_sorted)
    total_tips = sum(float(c.tips_total or 0) for c in closes_sorted)
    total_payments = sum(float(c.payment_total or 0) for c in closes_sorted)
    total_cash_diff = sum(
        float(c.cash_difference or 0) for c in closes_sorted
        if c.cash_difference is not None
    )
    avg_revenue = total_revenue / n if n else 0

    summary = [[
        f"Total Revenue\n{total_revenue:,.2f}".replace(",", " "),
        f"Total MOMS\n{total_moms:,.2f}".replace(",", " "),
        f"Total Tips\n{total_tips:,.2f}".replace(",", " "),
        f"Avg per Close\n{avg_revenue:,.2f}".replace(",", " "),
    ]]
    summary_table = Table(summary, colWidths=[60*mm, 60*mm, 60*mm, 60*mm])
    summary_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f7f3")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#1f6f43")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#1f6f43")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#bcd"))
        ,
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 8))

    # ─── Per-close table ─────────────────────────────────────────────
    table_data = [[
        "Date", "Revenue", "MOMS", "Net (uden moms)",
        "Payments", "Cash diff", "Tips", "Status",
    ]]

    def _fmt(v):
        return f"{float(v or 0):,.2f}".replace(",", " ")

    for c in closes_sorted:
        revenue = float(c.revenue_total or 0)
        moms = float(c.moms_total or 0) if c.moms_total is not None else None
        net = float(c.revenue_ex_moms or 0) if c.revenue_ex_moms is not None else None
        payments = float(c.payment_total or 0)
        cash_diff = c.cash_difference
        tips = float(c.tips_total or 0) if c.tips_total is not None else None
        status = (getattr(c, "status", None) or "confirmed")

        cash_diff_str = ""
        if cash_diff is not None:
            sign = "+" if cash_diff > 0 else ""
            cash_diff_str = f"{sign}{_fmt(cash_diff)}"

        table_data.append([
            c.date.strftime("%a %d %b %Y") if c.date else "",
            _fmt(revenue),
            _fmt(moms) if moms is not None else "—",
            _fmt(net) if net is not None else "—",
            _fmt(payments),
            cash_diff_str,
            _fmt(tips) if tips is not None else "—",
            "🔒 Locked" if status == "confirmed" else "📝 Draft",
        ])

    # Totals row
    table_data.append([
        f"Totals ({n})",
        _fmt(total_revenue),
        _fmt(total_moms),
        _fmt(total_revenue - total_moms),
        _fmt(total_payments),
        _fmt(total_cash_diff) if any(c.cash_difference is not None for c in closes_sorted) else "",
        _fmt(total_tips),
        "",
    ])

    col_widths = [38*mm, 28*mm, 24*mm, 32*mm, 28*mm, 24*mm, 24*mm, 22*mm]
    table = Table(table_data, colWidths=col_widths, repeatRows=1)

    style = TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
        ("ALIGN", (1, 0), (6, -1), "RIGHT"),
        ("ALIGN", (7, 0), (7, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -2), 4),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#888")),
        ("LINEABOVE", (0, -1), (-1, -1), 1, colors.HexColor("#1f6f43")),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#f0f7f3")),
        ("TEXTCOLOR", (0, -1), (-1, -1), colors.HexColor("#1f6f43")),
    ])
    table.setStyle(style)
    story.append(table)

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        f"Generated by BonBox · {n} close{'s' if n != 1 else ''} · "
        "Bogføringsloven §10 retention. "
        "MOMS = Danish VAT 25% (or applicable rate for branch).",
        note_style,
    ))

    doc.build(story)
    return buf.getvalue()
